### ISSUE TITLE
[Bug]: reporting value of RmaxCDM(SIDM)

### ISSUE THREAD

**Issue by Niusha951** [Niusha951/galacticus#3]
### What happened?

A bug happened!

####        #                  #                  
  #   #        #             #                       
 #       ###   #  ###   ### ###  ##   ### ## ##   ## 
 #       #  #  #  #  # #  #  #    #  #  #  #  #  #   
 #   ###  ###  #   ### #     #    #  #     #  #   #  
  #   #  #  #  #  #  # #     #    #  #     #  #    # 
   ####  #### ### ####  ###   ## ###  ###   #### ##  

 © 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
   2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
   - Andrew Benson

M: -> Begin task: report
M:     This is Galacticus: revision (unknown)                                  (branch: (unknown); build time: Thu Dec 05  1:07:16 UTC 2024)
M:     Built with: :GSL_version[2.6]:FoX_version[4.1.0]:HDF5_version[1.8.20]:FCCOMPILER[gfortran]:PREPROCESSOR[cpp]:CCOMPILER[gcc]:CPPCOMPILER[g++]:FCFLAGS[-ffree-line-length-none -frecursive -DBUILDPATH='./work/build' -J./work/build/moduleBuild/ -I./work/build/ -I/carnegie/hpcdata/software/rhel9/fftw/3.3.4/include -fintrinsic-modules-path /carnegie/hpcdata/software/rhel9/hdf5/1.8.20/include -fintrinsic-modules-path /carnegie/hpcdata/software/rhel9/fox/4.1.0/finclude -L/carnegie/hpcdata/software/rhel9/hdf5/1.8.20/lib -L/carnegie/hpcdata/software/rhel9/fox/4.1.0/lib -L/carnegie/hpcdata/software/rhel9/libmatheval/1.1.12/lib -L/carnegie/hpcdata/software/rhel9/fftw/3.3.4/lib -L/carnegie/hpcdata/software/rhel9/blas/3.12.0/lib -pthread -Wall -fbacktrace -ffpe-trap=invalid,zero,overflow -fdump-core -O3 -ffinite-math-only -fno-math-errno -fopenmp -g -DPROCPS -DOFDAVAIL -DFFTW3AVAIL -DANNAVAIL -DQHULLAVAIL -DMATHEVALAVAIL]:FCFLAGS_NOOPT[-ffree-line-length-none -frecursive -DBUILDPATH='./work/build' -J./work/build/moduleBuild/ -I./work/build/ -I/carnegie/hpcdata/software/rhel9/fftw/3.3.4/include -fintrinsic-modules-path /carnegie/hpcdata/software/rhel9/hdf5/1.8.20/include -fintrinsic-modules-path /carnegie/hpcdata/software/rhel9/fox/4.1.0/finclude -L/carnegie/hpcdata/software/rhel9/hdf5/1.8.20/lib -L/carnegie/hpcdata/software/rhel9/fox/4.1.0/lib -L/carnegie/hpcdata/software/rhel9/libmatheval/1.1.12/lib -L/carnegie/hpcdata/software/rhel9/fftw/3.3.4/lib -L/carnegie/hpcdata/software/rhel9/blas/3.12.0/lib -pthread -Wall -fbacktrace -ffpe-trap=invalid,zero,overflow -fdump-core -g]:CFLAGS[-fopenmp -DBUILDPATH='./work/build' -I./source/ -I./work/build/ -g -DOFDLOCKS -DPROCPS -DOFDAVAIL]:CPPFLAGS[-fopenmp -DBUILDPATH='./work/build' -I./source/ -I./work/build/ -I/carnegie/hpcdata/software/rhel9/qhull/8.0.2/include/libqhullcpp -I/carnegie/hpcdata/software/rhel9/ann/1.1.2 -I/carnegie/hpcdata/software/rhel9/libmatheval/1.1.12/include -g -DOFDLOCKS -DPROCPS -DOFDAVAIL -DANNAVAIL -DQHULLAVAIL -DMATHEVALAVAIL]:FCCOMPILER_VERSION[Using built-in specs. COLLECT_GCC=gfortran COLLECT_LTO_WRAPPER=/carnegie/hpcdata/software/rhel9/gcc/11.2.0/libexec/gcc/x86_64-pc-linux-gnu/11.2.0/lto-wrapper Target: x86_64-pc-linux-gnu Configured with: ../configure --prefix=/carnegie/hpcdata/software/rhel9/gcc/11.2.0 --disable-multilib --enable-languages=c,c++,fortran,jit --enable-checking=release --enable-host-shared --with-pic Thread model: posix Supported LTO compression algorithms: zlib zstd gcc version 11.2.0 (GCC) ]:CCOMPILER_VERSION[Using built-in specs. COLLECT_GCC=gcc COLLECT_LTO_WRAPPER=/carnegie/hpcdata/software/rhel9/gcc/11.2.0/libexec/gcc/x86_64-pc-linux-gnu/11.2.0/lto-wrapper Target: x86_64-pc-linux-gnu Configured with: ../configure --prefix=/carnegie/hpcdata/software/rhel9/gcc/11.2.0 --disable-multilib --enable-languages=c,c++,fortran,jit --enable-checking=release --enable-host-shared --with-pic Thread model: posix Supported LTO compression algorithms: zlib zstd gcc version 11.2.0 (GCC) ]:CPPCOMPILER_VERSION[Using built-in specs. COLLECT_GCC=g++ COLLECT_LTO_WRAPPER=/carnegie/hpcdata/software/rhel9/gcc/11.2.0/libexec/gcc/x86_64-pc-linux-gnu/11.2.0/lto-wrapper Target: x86_64-pc-linux-gnu Configured with: ../configure --prefix=/carnegie/hpcdata/software/rhel9/gcc/11.2.0 --disable-multilib --enable-languages=c,c++,fortran,jit --enable-checking=release --enable-host-shared --with-pic Thread model: posix Supported LTO compression algorithms: zlib zstd gcc version 11.2.0 (GCC) ]
M: <- Done task: report

### Relevant error message output

```shell
Does not stop the run or show any error messages! It freezes before printing the value of RmaxCDM!
```

Here is the output from gdb:
0x00007ffff6e86a80 in __lll_lock_wait () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.34-125.el9_5.1.x86_64 libtool-ltdl-2.4.6-46.el9.x86_64
(gdb) where
#0  0x00007ffff6e86a80 in __lll_lock_wait () from /lib64/libc.so.6
#1  0x00007ffff6e8d112 in pthread_mutex_lock@@GLIBC_2.2.5 () from /lib64/libc.so.6
#2  0x00007ffff749b1b6 in __gthread_mutex_lock (__mutex=0x2da5970)
    at ../libgcc/gthr-default.h:749
#3  get_gfc_unit (n=6, do_create=1) at ../../../libgfortran/io/unit.c:395
#4  0x00007ffff749983d in data_transfer_init (dtp=dtp@entry=0x7fffffff5db0, 
    read_flag=read_flag@entry=0) at ../../../libgfortran/io/transfer.c:2851
#5  0x00007ffff749a258 in _gfortran_st_write (dtp=dtp@entry=0x7fffffff5db0)
    at ../../../libgfortran/io/transfer.c:4411
#6  0x0000000000644d4e in dark_matter_profiles_dmo.darkmatterprofiledmonfw_::nfwradiuscircularvelocitymaximum (self=..., node=...) at ./work/build/dark_matter_profiles_DMO.NFW.p.F90:683
#7  0x000000000063c73f in dark_matter_profiles_dmo.darkmatterprofiledmoheated_::heatedradiuscircularvelocitymaximum (self=..., node=...)
    at ./work/build/dark_matter_profiles_DMO.heated.p.F90:872
#8  0x0000000000fc8039 in nodes_operators.nodeoperatorsidmparametric_::sidmparametricalculatetaudifferentialevolution (self=..., node=..., interrupt=<optimized out>, 
    functioninterrupt=<optimized out>, propertytype=<optimized out>)
    at ./work/build/nodes.operators.physics.dark_matter.SIDM_parametric.p.F90:1218
#9  0x0000000000f30ac6 in nodes_operators.nodeoperatormulti_::multidifferentialevolution (
    self=..., node=..., interrupt=.TRUE., functioninterrupt=0x7fffffff6398, propertytype=3)
    at ./work/build/nodes.operators.multi.p.F90:396
#10 0x0000000000c97725 in merger_trees_evolve_node.mergertreenodeevolverstandard_::standardderivativescompute (node=..., interrupt=.TRUE., 
    functioninterruptreturn=functioninterruptreturn@entry=0x7fffffff6448, propertytype=3)
    at ./work/build/merger_trees.node_evolver.standard.p.F90:1859
#11 0x0000000000c986c5 in merger_trees_evolve_node.mergertreenodeevolverstandard_::standardodes (time=0.60688478580983396, y=..., dydt=...)
    at ./work/build/merger_trees.node_evolver.standard.p.F90:1659
#12 0x000000000117e697 in numerical_ode_solvers::derivativeswrapper (x=<optimized out>, 
    y=..., dydx=..., parameterpointer=<optimized out>)
    at ./work/build/numerical.ODE_solver.p.F90:822
#13 0x00007ffff7b38874 in gsl_odeiv2_evolve_apply (e=0x3784c30, con=0x35b7440, 
    step=0x393b600, dydt=0x35b6110, t=0x7fffffff66f8, t1=0.69783573396841003, h=0x38b4db0, 
    y=0x30d69d0) at ode-initval2/evolve.c:148
#14 0x0000000000936d3b in gsl_odeiv2_driver2_apply (d=0x38b4d90, t=0x7fffffff66f8, 
    t1=0.69783573396841003, y=0x30d69d0, 
    postStep=0xc95da0 <merger_trees_evolve_node.mergertreenodeevolverstandard_::standardpoststepprocessing>, latentIntegrator=0x0, stepAnalyzer=0x0)
    at source/gslODEInitVal2/driver2.c:192
#15 0x000000000117edf3 in numerical_ode_solvers::odesolversolve (self=..., 
    x0=<optimized out>, x1=<optimized out>, y=..., z=..., xstep=<optimized out>, 
    status=<optimized out>) at ./work/build/numerical.ODE_solver.p.F90:684
#16 0x0000000000c9c2eb in merger_trees_evolve_node.mergertreenodeevolverstandard_::standardevolve (self=..., tree=..., node=0x2f76510, timeend=<optimized out>, 
    interrupted=<optimized out>, functioninterrupt=<optimized out>, 
    galacticstructuresolver__=..., treelock=..., systemclockmaximum=<optimized out>, 
    status=<optimized out>) at ./work/build/merger_trees.node_evolver.standard.p.F90:1398
#17 0x0000000000c3e685 in merger_trees_evolve.mergertreeevolverstandard_::standardevolve (
    self=..., tree=..., timeend=2, treedidevolve=.FALSE., suspendtree=.FALSE., 
    deadlockreporting=.FALSE., systemclockmaximum=0, 
    initializationlock=<error reading variable: Cannot access memory at address 0x0>, 
    status=0) at ./work/build/merger_trees.evolver.standard.p.F90:964
#18 0x00000000020e5b44 in __tasks_MOD_evolveforestsperform._omp_fn.0 ()
    at ./work/build/tasks.evolve_forests.p.F90:1553
#19 0x00007ffff7d03306 in GOMP_parallel (
--Type <RET> for more, q to quit, c to continue without paging--c
    fn=0x20e4810 <__tasks_MOD_evolveforestsperform._omp_fn.0>, data=0x7fffffff7f00, 
    num_threads=1, flags=0) at ../../../libgomp/parallel.c:178
#20 0x00000000020e8914 in tasks.taskevolveforests_::evolveforestsperform (self=..., 
    status=<optimized out>) at ./work/build/tasks.evolve_forests.p.F90:1887
#21 0x00000000008bb2d9 in galacticus () at ./work/build/Galacticus.p.F90:141
#22 0x0000000000411b57 in main (argc=<optimized out>, argv=<optimized out>)
    at ./work/build/Galacticus.p.F90:34
#23 0x00007ffff6e295d0 in __libc_start_call_main () from /lib64/libc.so.6
#24 0x00007ffff6e29680 in __libc_start_main_impl () from /lib64/libc.so.6
#25 0x0000000000411df5 in _start ()

**Comment by Niusha951** [comment]
To prevent conflicts caused by overlapping print statements when running Galacticus with multiple threads, each print statement uses a locking mechanism. However, the DMO function being called here also performs its own printing, leading to multiple print statements being processed simultaneously, which causes issues. To resolve this, we can define an additional variable to store the values of RmaxCDM and SIDM, and then print these values in a single statement.
